allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': set this to true or false
  '@sentry-internal/node-cpu-profiler': set this to true or false
  esbuild: true
  prisma: true
